### ISSUE TITLE
Remove "x86_64" as invalid model for devices that support Face ID

### ISSUE THREAD

**Issue by Maj0rPaine** [Chris-Corea/BiometricAuthenticator#4]
"x86_64" should be removed as an invalid model for devices that support Face ID since the simulator does in fact support this type of biometric authentication.

**Comment by Chris-Corea** [comment]
Thanks for creating the issue! I'll update this quickly and push out an update.

**Comment by Maj0rPaine** [comment]
Here you go. Thanks for your work on this project. 
#5

**Comment by Chris-Corea** [comment]
Merged #5. Closing the issue.

**Comment by Chris-Corea** [comment]
Updated pod pushed!
